### ISSUE TITLE
Maven wrapper shell script is not executable

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-starter#34]
The generated zip contains a maven wrapper script however the script is not executable so it cannot be used before the user first change the file attributed:

‘chmod a+x mvnw’

This should be set in the zip itself.

**Comment by pmlopes** [comment]
Be aware if when you do this that you need to monitor if google will flag the download as malware. If that happens (only on google chrome you will get a red flag when downloading) you need to fill a request explaining what the file contains and it’s source and usually it gets clear within 24h

**Comment by danielpetisme** [comment]
With current version deployed the issue should be fixed

**Comment by danielpetisme** [comment]
Fixed

**Comment by tsegismont** [comment]
Reopening (not working in 2.0.0).

File permissions are preserved in the fat jar. But when serving files from the classpath, Vert.x cannot retrieve them (the JDK ZipFile API does not support extra fields).

We can either:
- change file serving by deploying static files as a separate zip and disable classpath resolving
- modify code to set permissions explicitly instead of inspecting original file permissions

I will sleep on it but the latter option has my preference.
